Atmel BLDC control on ATAVRMC310 with ATmega32M1: ushell_task.h File Reference
ushell_task.h File Reference
Defines
#define ABORT_CHAR CTRL_C
#define BKSPACE_CHAR 0x08
#define CMD_BACKWARD 0x05
#define CMD_FORWARD 0x04
#define CMD_GET_ID 0x07
#define CMD_GET_STATUS0 0x08
#define CMD_GET_STATUS1 0x09
#define CMD_HELP 0x01
#define CMD_NONE 0x00
#define CMD_RUN 0x02
#define CMD_SET_SPEED 0x06
#define CMD_STOP 0x03
#define CR 0x0D
#define CTRL_C 0x03
#define CTRL_Q 0x11
#define LF 0x0A
#define MSG_ER_CMD_NOT_FOUND "Unknown Command"
#define MSG_HELP "\r\ru : run\r\st : stop\r\fw : forward\r\bw : backward\r\ss : set speed\r\gi : get id\"
#define MSG_PROMPT "\r>"
#define MSG_WELCOME "\rATMEL Motor Control Interface"
#define QUIT_APPEND CTRL_Q
#define STR_BACKWARD "bw"
#define STR_FORWARD "fw"
#define STR_GET_ID "gi"
#define STR_GET_STATUS0 "g0"
#define STR_GET_STATUS1 "g1"
#define STR_HELP "help"
#define STR_RUN "ru"
#define STR_SET_SPEED "ss"
#define STR_STOP "st"
Functions
void build_cmd (void)
U8 mystrncmp (U8 *str1, U8 code *str2, U8 i)
void parse_cmd (void)
void print_msg (U8 code *str)
void ushell_task (void)
void ushell_task_init (void)
Variables
volatile Bool ushell_active
Define Documentation
#define ABORT_CHAR CTRL_C
Definition at line 43 of file ushell_task.h.
Referenced by build_cmd().
#define BKSPACE_CHAR 0x08
Definition at line 42 of file ushell_task.h.
Referenced by build_cmd().
#define CMD_BACKWARD 0x05
Definition at line 30 of file ushell_task.h.
Referenced by parse_cmd(), and ushell_task().
#define CMD_FORWARD 0x04
Definition at line 29 of file ushell_task.h.
Referenced by parse_cmd(), and ushell_task().
#define CMD_GET_ID 0x07
Definition at line 32 of file ushell_task.h.
Referenced by parse_cmd(), and ushell_task().
#define CMD_GET_STATUS0 0x08
Definition at line 33 of file ushell_task.h.
Referenced by parse_cmd(), and ushell_task().
#define CMD_GET_STATUS1 0x09
Definition at line 34 of file ushell_task.h.
Referenced by parse_cmd(), and ushell_task().
#define CMD_HELP 0x01
Definition at line 26 of file ushell_task.h.
Referenced by parse_cmd(), and ushell_task().
#define CMD_NONE 0x00
Definition at line 25 of file ushell_task.h.
Referenced by ushell_task(), and ushell_task_init().
#define CMD_RUN 0x02
Definition at line 27 of file ushell_task.h.
Referenced by parse_cmd(), and ushell_task().
#define CMD_SET_SPEED 0x06
Definition at line 31 of file ushell_task.h.
Referenced by parse_cmd(), and ushell_task().
#define CMD_STOP 0x03
Definition at line 28 of file ushell_task.h.
Referenced by parse_cmd(), and ushell_task().
#define CR 0x0D
Definition at line 38 of file ushell_task.h.
Referenced by build_cmd().
#define CTRL_C 0x03
Definition at line 41 of file ushell_task.h.
#define CTRL_Q 0x11
Definition at line 40 of file ushell_task.h.
#define LF 0x0A
Definition at line 39 of file ushell_task.h.
#define MSG_ER_CMD_NOT_FOUND "Unknown Command"
Definition at line 60 of file ushell_task.h.
#define MSG_HELP "\r\ru : run\r\st : stop\r\fw : forward\r\bw : backward\r\ss : set speed\r\gi : get id\"
Definition at line 61 of file ushell_task.h.
#define MSG_PROMPT "\r>"
Definition at line 58 of file ushell_task.h.
#define MSG_WELCOME "\rATMEL Motor Control Interface"
Definition at line 59 of file ushell_task.h.
#define QUIT_APPEND CTRL_Q
Definition at line 44 of file ushell_task.h.
#define STR_BACKWARD "bw"
Definition at line 51 of file ushell_task.h.
#define STR_FORWARD "fw"
Definition at line 50 of file ushell_task.h.
#define STR_GET_ID "gi"
Definition at line 53 of file ushell_task.h.
#define STR_GET_STATUS0 "g0"
Definition at line 54 of file ushell_task.h.
#define STR_GET_STATUS1 "g1"
Definition at line 55 of file ushell_task.h.
#define STR_HELP "help"
Definition at line 49 of file ushell_task.h.
#define STR_RUN "ru"
Definition at line 47 of file ushell_task.h.
#define STR_SET_SPEED "ss"
Definition at line 52 of file ushell_task.h.
#define STR_STOP "st"
Definition at line 48 of file ushell_task.h.
Function Documentation
void build_cmd (void)
get the full command line to be interpreted.
Parameters:
none
Returns:
none
Definition at line 159 of file ushell_task.c.
References ABORT_CHAR, BKSPACE_CHAR, cmd_str, CR, i_str, parse_cmd(), uart_getchar(), and uart_test_hit().
{
U8 c;
   if (uart_test_hit())    //Something new of  the UART ?
   {
      c=uart_getchar();
      switch (c)
      {
         case CR:
            cmd_str[i_str]=0;  //Add NULL char
            parse_cmd();    //Decode the command
            i_str=0;
            break;
         case ABORT_CHAR:    //^c abort cmd
            i_str=0;
            printf("\r#");
            break;
         case BKSPACE_CHAR:   //backspace
            if(i_str>0)
            {
               putchar(c);
               putchar(' ');
               putchar(c);
            }
            if(i_str>=1)
            {
               i_str--;
            }
            break;
         default:
            cmd_str[i_str++]=c;  //append to cmd line
            break;
      }
   }
}
U8 mystrncmp (U8 * str1, U8 code * str2, U8 i)
compares two strings located in flash code area.
Parameters:
*str1
*str2
Returns:
status: TRUE for ok, FALSE if strings are not equal
Definition at line 283 of file ushell_task.c.
References FALSE, and TRUE.
{
   U8 j;
   for(j=0;j<=i;j++)
   {
#ifndef AVRGCC
      if(*str1!=*str2)
#else
      if( pgm_read_byte_near((unsigned int)str1) != pgm_read_byte_near((unsigned int)str2))
#endif
      {
         return FALSE;
      }
      str1++;str2++;
   }
   return TRUE;
}
void parse_cmd (void)
decodes full command line into command type and arguments This function allows to set the cmd_type to the command type decoded with its respective arguments par_str1 and par_str2
Parameters:
none
Returns:
none
Definition at line 207 of file ushell_task.c.
References cmd, CMD_BACKWARD, CMD_FORWARD, CMD_GET_ID, CMD_GET_STATUS0, CMD_GET_STATUS1, CMD_HELP, CMD_RUN, CMD_SET_SPEED, CMD_STOP, cmd_str, cmd_type, FALSE, i_str, LSB, MSB, msg_er_cmd_not_found, msg_prompt, mystrncmp(), par_str1, par_str2, print_msg(), str_backward, str_forward, str_get_id, str_get_status0, str_get_status1, str_help, str_run, str_set_speed, str_stop, and TRUE.
{
   U8 i=0;
   U8 j;
   //Get command type
   for(i=0;cmd_str[i]!=' ' && i<=i_str;i++);
   cmd=TRUE;
   //Decode command type
   if ( mystrncmp(cmd_str,str_run,i-1))
   {  cmd_type=CMD_RUN; }
   else if ( mystrncmp(cmd_str,str_stop,i-1))
   {  cmd_type=CMD_STOP; }
   else if ( mystrncmp(cmd_str,str_help,i-1))
   {  cmd_type=CMD_HELP; }
   else if ( mystrncmp(cmd_str,str_forward,i-1))
   {  cmd_type=CMD_FORWARD; }
   else if ( mystrncmp(cmd_str,str_backward,i-1))
   {  cmd_type=CMD_BACKWARD; }
   else if ( mystrncmp(cmd_str,str_set_speed,i-1))
   {  cmd_type=CMD_SET_SPEED; }
   else if ( mystrncmp(cmd_str,str_get_id,i-1))
   {  cmd_type=CMD_GET_ID; }
   else if ( mystrncmp(cmd_str,str_get_status0,i-1))
   {  cmd_type=CMD_GET_STATUS0; }
   else if ( mystrncmp(cmd_str,str_get_status1,i-1))
   {  cmd_type=CMD_GET_STATUS1; }
   else
   {
      if(i_str)
      {
        print_msg(msg_er_cmd_not_found);
      }
      print_msg(msg_prompt);
      cmd=FALSE;
      return;
   }
  //Get first arg (if any)
   if(++i<i_str)
   {
      j=0;
      for(;(cmd_str[i]!=' ')&&(i<i_str);i++)
      {
         LSB(par_str1[j])=cmd_str[i];
         MSB(par_str1[j])=0;
         j++;
      }
      LSB(par_str1[j])=0;MSB(par_str1[j])=0;
   }
   else   {  return; }
   //Get second arg (if any)
   if(++i<i_str)
   {
      j=0;
      for(;(cmd_str[i]!=' ')&&(i<i_str);i++)
      {
         LSB(par_str2[j])=cmd_str[i];
         MSB(par_str2[j])=0;
         j++;
      }
      LSB(par_str2[j])=0;MSB(par_str2[j])=0;
   }
   else   { return; }
}
void print_msg (U8 code * str)
Display an ASCII code string.
Parameters:
*str,: pointer to string located in flash area
Returns:
none
Definition at line 306 of file ushell_task.c.
{
U8 c;
#ifndef AVRGCC
   c=*str++;
   while(c!=0)
   {
      putchar(c);
      c=*str++;
   }
#else    // AVRGCC does not support point to PGM space
   c=pgm_read_byte_near((unsigned int)str++);
   while(c!=0)
   {
      putchar(c);
      c=pgm_read_byte_near((unsigned int)str++);
   }
#endif
}
void ushell_task (void)
Entry point of the explorer task management This function links perform ushell task decoding to access file system functions.
Parameters:
none
Returns:
none
Definition at line 90 of file ushell_task.c.
References BOARD_ID, build_cmd(), CCW, cmd, CMD_BACKWARD, CMD_FORWARD, CMD_GET_ID, CMD_GET_STATUS0, CMD_GET_STATUS1, CMD_HELP, CMD_NONE, CMD_RUN, CMD_SET_SPEED, CMD_STOP, cmd_type, convert_param1(), FALSE, mc_disable_during_inrush(), mci_backward(), mci_direction, mci_forward(), mci_get_measured_current(), mci_get_measured_speed(), mci_run(), mci_run_stop, mci_set_ref_speed(), mci_stop(), msg_er_cmd_not_found, msg_help, msg_prompt, param1, print_hex16(), print_msg(), REV_ID, SOFT_ID, TRUE, and ushell_active.
{
   U8 status = 0;
   if(cmd==FALSE)
   {
      build_cmd();
   }
   else
   {
      switch (cmd_type)
      {
         case CMD_HELP:
            print_msg(msg_help);
            break;
         case CMD_RUN:
            mci_run();
            break;
         case CMD_STOP:
            mci_stop();
            break;
         case CMD_FORWARD:
            mci_forward();
            break;
         case CMD_BACKWARD:
            mci_backward();
            break;
         case CMD_SET_SPEED:
            convert_param1();
            mc_disable_during_inrush();
            mci_set_ref_speed((U8)param1);
            break;
         case CMD_GET_ID:
            print_hex16(BOARD_ID);
            putchar(' ');
            print_hex16(SOFT_ID);
            putchar(' ');
            print_hex16(REV_ID);
            break;
         case CMD_GET_STATUS0:
            status = 0;
            if (mci_direction == CCW) {status |= (1<<3);}
            if (mci_run_stop == TRUE) {status |= (1<<2);}
            print_hex16(status);
            putchar(' ');
            print_hex16(mci_get_measured_speed());
            putchar(' ');
            print_hex16(mci_get_measured_current());
            ushell_active = TRUE;
            break;
         case CMD_GET_STATUS1:
            print_hex16(0xDEA);
            putchar(' ');
            print_hex16(0x123);
            break;
         default:    //Unknown command
            print_msg(msg_er_cmd_not_found);
      }
      cmd_type=CMD_NONE;
      cmd=FALSE;
      print_msg(msg_prompt);
   }
}
void ushell_task_init (void)
This function initializes the hardware/software ressources required for ushell task.
Parameters:
none
Returns:
none
/
Definition at line 69 of file ushell_task.c.
References cmd, CMD_NONE, cmd_type, FALSE, msg_prompt, msg_welcome, print_msg(), and uart_init().
{
   uart_init();
   print_msg(msg_welcome);
   print_msg(msg_prompt);
   cmd=FALSE;
   cmd_type=CMD_NONE;
}
Variable Documentation
volatile Bool ushell_active
Definition at line 42 of file ushell_task.c.