Atmel BLDC control on ATAVRMC310 with ATmega32M1: ascii.c File Reference
ascii.c File Reference
#include "config.h"
#include "ascii.h"
Functions
U8 ascii_to_bin (U8 c)
U8 bin_to_ascii (U8 c)
Function Documentation
U8 ascii_to_bin (U8 c)
This function returns the binary value of an ascii digit.
Parameters:
none
Returns:
none
/
Definition at line 34 of file ascii.c.
Referenced by convert_param1(), and convert_param2().
{
  if (c>='a') return(c-('a'-0x0A));
  if (c>='A') return(c-('A'-0x0A));
  return(c-'0');
}
U8 bin_to_ascii (U8 c)
This function returns the ascii value of a quartet
Parameters:
none
Returns:
none /
Definition at line 49 of file ascii.c.
Referenced by print_hex16().
{
  if (c>=0x0A) return (c+('A'-0x0A));
  return (c+'0');
}