Atmel BLDC control on ATAVRMC310 with ATmega32M1: mc_interface.h File Reference
mc_interface.h File Reference
Functions
U8 mc_get_potentiometer_value (void)
void mc_init (void)
void mc_set_measured_speed (U8 measured_speed)
void mc_set_potentiometer_value (U8 potentiometer)
void mci_backward (void)
void mci_forward (void)
U16 mci_get_measured_current (void)
U8 mci_get_measured_speed (void)
U8 mci_get_motor_direction (void)
U8 mci_get_ref_speed (void)
Bool mci_motor_is_running (void)
void mci_retry_run (void)
void mci_run (void)
void mci_set_ref_speed (U8 speed)
void mci_stop (void)
void mci_store_measured_current (U16 current)
Variables
Bool mci_direction
User Input parameter to set motor direction.
Bool mci_run_stop
User Input parameter to launch or stop the motor.
Function Documentation
U8 mc_get_potentiometer_value (void)
Get the potentiometer value
Precondition:
Launch ADC scheduler
Postcondition:
Get ADC Channel 6 result (Potentiometer value on 8bits).
Definition at line 198 of file mc_interface.c.
References mc_potentiometer_value.
{
  return mc_potentiometer_value;
}
void mc_init (void)
use to init programm
Parameters:
@post configuration of hardware and sotware
Precondition:
none
Definition at line 91 of file mc_interface.c.
References mc_init_HW(), mc_set_measured_speed(), mci_forward(), mci_set_ref_speed(), and mci_stop().
{
  mc_init_HW();
  Enable_interrupt();
  mci_stop();
  mci_forward();
  mci_set_ref_speed(0);
  mc_set_measured_speed(0);
}
void mc_set_measured_speed (U8 measured_speed)
set Measured of speed (for initialization)
Precondition:
none
Postcondition:
mci_measured_speed initialized
Definition at line 157 of file mc_interface.c.
References mci_measured_speed.
{
  mci_measured_speed = measured_speed;
}
void mc_set_potentiometer_value (U8 potentiometer)
Set the 'mc_potentiometer_value' variable with the potentiometer value
Precondition:
Launch ADC scheduler
Postcondition:
'mc_potentiometer_value' set with the potentiometer value
Definition at line 208 of file mc_interface.c.
References mc_potentiometer_value.
{
  mc_potentiometer_value = potentiometer;
}
void mci_backward (void)
Definition at line 137 of file mc_interface.c.
References CCW, and mci_direction.
{
  mci_direction = CCW;
}
void mci_forward (void)
Definition at line 127 of file mc_interface.c.
References CW, and mci_direction.
{
  mci_direction = CW;
}
U16 mci_get_measured_current (void)
Get the current measured in the motor
Precondition:
Launch ADC scheduler
Postcondition:
Get ADC Channel 12 result (Current value on 8bits).
Definition at line 178 of file mc_interface.c.
References mci_measured_current.
{
  return mci_measured_current/64;
}
U8 mci_get_measured_speed (void)
Measured of speed
Returns:
return value of speed (8 bits)
Precondition:
none
Postcondition:
none
Definition at line 168 of file mc_interface.c.
References mci_measured_speed.
{
  return mci_measured_speed;
}
U8 mci_get_motor_direction (void)
Definition at line 147 of file mc_interface.c.
References mci_direction.
{
  return mci_direction;
}
U8 mci_get_ref_speed (void)
Definition at line 117 of file mc_interface.c.
References mci_ref_speed.
{
  return mci_ref_speed;
}
Bool mci_motor_is_running (void)
get the motor state
Precondition:
initialization HW and SW
Postcondition:
We know if the motor is running or not
Definition at line 69 of file mc_interface.c.
References mci_run_stop.
{
  return mci_run_stop;
}
void mci_retry_run (void)
mci_retry_run retry to run if speed is null
Precondition:
initialization HW and SW
Postcondition:
New value in Hall variable
Definition at line 55 of file mc_interface.c.
References mc_disable_during_inrush(), mc_duty_cycle(), mc_get_duty_cycle(), mc_get_hall(), mc_regulation_loop(), mc_switch_commutation(), mci_run_stop, and TRUE.
{
  mci_run_stop = TRUE;
  mc_regulation_loop();
  mc_duty_cycle(mc_get_duty_cycle());
  mc_switch_commutation(mc_get_hall());
  mc_disable_during_inrush(); /* disable overcurrent during inrush */
}
void mci_run (void)
mci_run run the motor with parameter
Precondition:
initialization HW and SW
Postcondition:
New value in Hall variable
Definition at line 36 of file mc_interface.c.
References FALSE, mc_disable_during_inrush(), mc_duty_cycle(), mc_get_duty_cycle(), mc_get_hall(), mc_regulation_loop(), mc_switch_commutation(), mci_run_stop, overcurrent, PSC_Init(), and TRUE.
{
  if (!(PCTL & (1<<PRUN))) /* if there is an overcurrent */
  {
    PSC_Init();
  }
  overcurrent = FALSE;
  mci_run_stop = TRUE;
  mc_regulation_loop();
  mc_duty_cycle(mc_get_duty_cycle());
  mc_switch_commutation(mc_get_hall());
  mc_disable_during_inrush(); /* disable overcurrent during inrush */
}
void mci_set_ref_speed (U8 speed)
Definition at line 107 of file mc_interface.c.
References mci_ref_speed.
{
  mci_ref_speed = speed;
}
void mci_stop (void)
mci_stop stop the motor And reset the speed measured value.
Precondition:
motor run (mci_run executed)
Postcondition:
motor stop
Definition at line 80 of file mc_interface.c.
References FALSE, and mci_run_stop.
{
  mci_run_stop=FALSE;
}
void mci_store_measured_current (U16 current)
Set the variable 'mc_measured_current' for initialization.
Precondition:
none
Postcondition:
'mc_measured_current' set with the current value
Definition at line 188 of file mc_interface.c.
References mci_measured_current.
{
  mci_measured_current = ((63*mci_measured_current)+(64*current))>>6;
}
Variable Documentation
Bool mci_direction
User Input parameter to set motor direction.
Definition at line 20 of file mc_interface.c.
Bool mci_run_stop
User Input parameter to launch or stop the motor.
Definition at line 21 of file mc_interface.c.