Atmel BLDC control on ATAVRMC310 with ATmega32M1: mc_control.h File Reference
mc_control.h File Reference
Functions
U8 mc_control_current (U8 cur_cmd)
U8 mc_control_speed (U8 speed_cmd)
U8 mc_get_duty_cycle ()
void mc_regulation_loop ()
void mc_set_current_loop ()
void mc_set_open_loop ()
void mc_set_speed_loop ()
Function Documentation
U8 mc_control_current (U8 cur_cmd)
use to control current , current regulation loop need parameter : Kp_cur, Ki_cur ,Kd_cur and K_cur_scal in config_motor.h need to call in Te ms
Returns:
value of current, duty cycle on 8 bits
Definition at line 111 of file mc_control.c.
References cur_error, cur_integ, cur_integral, cur_proportional, K_cur_scal, Ki_cur, Kp_cur, and mci_get_measured_current().
{
  U8 Duty = 0;
  S32 increment = 0;
  // Error calculation
  cur_error = cur_cmd - (mci_get_measured_current());// value -255 <=> 255
  // proportional term calculation
  cur_proportional = Kp_cur*cur_error;
  // integral term calculation
  cur_integral = cur_integral + cur_error;
  if(cur_integral >  255) cur_integral =  255;
  if(cur_integral < -255) cur_integral = -255;
  cur_integ = Ki_cur*cur_integral;
  // derivative term calculation
  /*cur_derivative = cur_error - last_cur_error;
  if(cur_derivative >  255) cur_derivative =  255;
  if(cur_derivative < -255) cur_derivative = -255;
  cur_der = Kd_cur*cur_derivative;
  last_cur_error = cur_error;*/
  // Duty Cycle calculation
  increment = cur_proportional + cur_integ;
  //increment += cur_der;
  increment = increment >> K_cur_scal;
  // Variable saturation
  if(increment >= (S16)(255)) Duty = 255;
  else
  {
    if(increment <= (S16)(0)) Duty =   0;
    else Duty = (U8)(increment);
  }
  // return Duty Cycle
  return Duty;
}
U8 mc_control_speed (U8 speed_cmd)
use to control speed , speed regulation loop need parameter : Kp_speed, Ki_speed ,Kd_speed and K_speed_scal in config_motor.h need to call in Te ms
Returns:
value of speed, duty cycle on 8 bits
Definition at line 51 of file mc_control.c.
References K_speed_scal, Ki_speed, Kp_speed, mci_get_measured_speed(), speed_error, speed_integ, speed_integral, and speed_proportional.
{
  U8 Duty = 0;
  S32 increment = 0;
  // Error calculation
  speed_error = speed_cmd - mci_get_measured_speed();// value -255 <=> 255
  // proportional term calculation
  speed_proportional = Kp_speed*speed_error;
  // integral term calculation
/*  speed_integral = speed_integral + speed_error;
  if(speed_integral >  255) speed_integral =  255;
  if(speed_integral < -255) speed_integral = -255;
  speed_integ = Ki_speed*speed_integral;
*/
  speed_integral = Ki_speed*(speed_integral + speed_error);
  if(speed_integral >  255) speed_integral =  255;
  if(speed_integral < -255) speed_integral = -255;
  // derivative term calculation
  /*speed_derivative = speed_error - last_speed_error;
  if(speed_derivative >  255) speed_derivative =  255;
  if(speed_derivative < -255) speed_derivative = -255;
  speed_der = Kd_speed*speed_derivative;
  last_speed_error = speed_error;*/
  // Duty Cycle calculation
  increment = speed_proportional + speed_integ;
  //increment += speed_der;
  increment = increment >> K_speed_scal;
  // Variable saturation
  if(increment >= (S16)(255)) Duty = 255;
  else
  {
    if(increment <= (S16)(0)) Duty =   0;
    else Duty = (U8)(increment);
  }
  // return Duty Cycle
  return Duty;
}
U8 mc_get_duty_cycle ()
set type of regulation
Definition at line 191 of file mc_control.c.
References duty_cycle.
{
  return duty_cycle;
}
void mc_regulation_loop ()
launch speed control or no regulation
Postcondition:
new duty cycle on PWM
Definition at line 165 of file mc_control.c.
References CURRENT_LOOP, duty_cycle, mc_control_current(), mc_control_speed(), mc_get_potentiometer_value(), mci_get_ref_speed(), OPEN_LOOP, regulation_type, and SPEED_LOOP.
{
  switch(regulation_type)
  {
    case OPEN_LOOP     : duty_cycle = mci_get_ref_speed();break;
    case SPEED_LOOP    : duty_cycle = mc_control_speed(2*mci_get_ref_speed());break;
    case CURRENT_LOOP  : duty_cycle = mc_control_current(mc_get_potentiometer_value());break;
    default : break;
  }
}
void mc_set_current_loop ()
set type of regulation
Definition at line 187 of file mc_control.c.
References CURRENT_LOOP, and regulation_type.
{regulation_type = CURRENT_LOOP;}
void mc_set_open_loop ()
set type of regulation
Postcondition:
Open loop regulation Set
Definition at line 179 of file mc_control.c.
References OPEN_LOOP, and regulation_type.
{regulation_type = OPEN_LOOP;}
void mc_set_speed_loop ()
set type of regulation
Definition at line 183 of file mc_control.c.
References regulation_type, and SPEED_LOOP.
{regulation_type = SPEED_LOOP;}