Atmel BLDC control on ATAVRMC310 with ATmega32M1: main.c File Reference
main.c File Reference
#include "config.h"
#include "mc_interface.h"
#include "mc_control.h"
#include "mc_drv.h"
#include "adc\adc_drv.h"
#include "ushell_task.h"
Functions
void main (void)
Main Entry.
Variables
U16 g_regulation_period = 0
Define the sampling period.
Bool g_tick
Use for control the sampling period value.
U16 motor_speed = 0
User Speed Order.
Bool overcurrent
Function Documentation
void main (void)
Main Entry.
The main entry point for the control motor application.
The mc_regulation_loop() function is launched every 80ms.
Definition at line 42 of file main.c.
References Clear_PC7, FALSE, g_regulation_period, g_tick, mc_ADC_Scheduler(), mc_duty_cycle(), mc_get_duty_cycle(), mc_get_potentiometer_value(), mc_init(), mc_inrush_task(), mc_regulation_loop(), mci_run(), mci_set_ref_speed(), overcurrent, Set_PC7, TRUE, ushell_active, ushell_task(), and ushell_task_init().
{
  // init motor
  mc_init();  // launch initialization of the motor application
  // Initialyze the communication system for External Command through Uart
  ushell_task_init();
  // Start the motor
  mci_set_ref_speed(0);
  mci_run();
//  mc_set_speed_loop(); // uncomment to activate the speed regulation loop
  while(1)
  {
    // Launch regulation loop
    // Timer 1 generate an IT (g_tick) all 250us
    // Sampling period = n * 250us
    if (g_tick == TRUE)
    {
      g_tick = FALSE;
      // Get Current and potentiometer value
      mc_ADC_Scheduler();
      g_regulation_period += 1;
      if ( g_regulation_period >= 40 ) //n * 250us = Te
      {
        g_regulation_period = 0;
        if (ushell_active == FALSE)
        {
          // Set User Speed Command with potentiometer
          mci_set_ref_speed(mc_get_potentiometer_value());
        }
        mc_regulation_loop(); // launch regulation loop
      }
      mc_duty_cycle(mc_get_duty_cycle());
      ushell_task();
      mc_inrush_task();       // manage the inrush current
    }
    if (overcurrent==0)
    {
      Set_PC7();
    }
    else
    {
      Clear_PC7();
    }
  }
}
Variable Documentation
U16 g_regulation_period = 0
Define the sampling period.
Definition at line 31 of file main.c.
Referenced by main().
Bool g_tick
Use for control the sampling period value.
Definition at line 41 of file mc_drv.c.
Referenced by launch_sampling_period(), and main().
U16 motor_speed = 0
User Speed Order.
Definition at line 32 of file main.c.
Bool overcurrent
Definition at line 31 of file mc_drv.c.
Referenced by main(), mc_overcurrent_detect(), and mci_run().