Atmel BLDC control on ATAVRMC310 with ATmega32M1: mc_drv.c File Reference
mc_drv.c File Reference
#include "config.h"
#include "mc_drv.h"
#include "mc_interface.h"
#include "mc_control.h"
#include "psc\psc_drv.h"
#include "adc\adc_drv.h"
#include "dac\dac_drv.h"
#include "pll\pll_drv.h"
#include "comparator\comparator_drv.h"
Defines
#define PSWAP0 2
#define PSWAP1 3
#define PSWAP2 4
Functions
__interrupt void ADC_end_of_conversion (void)
__interrupt void launch_sampling_period (void)
void mc_ADC_Scheduler (void)
void mc_disable_during_inrush (void)
void mc_duty_cycle (U8 level)
void mc_estimation_speed (void)
Hall_Position mc_get_hall (void)
__interrupt void mc_hall_a (void)
__interrupt void mc_hall_b (void)
__interrupt void mc_hall_c (void)
void mc_init_HW (void)
void mc_init_timer0 (void)
void mc_init_timer1 (void)
void mc_inrush_task (void)
__interrupt void mc_overcurrent_detect (void)
void mc_switch_commutation (Hall_Position position)
__interrupt void ovfl_timer0 (void)
void PSC_Init (void)
Variables
static char ADC_State = FREE
U16 average = 0
U8 count = 1
Bool current_EOC = FALSE
Bool g_mc_read_enable = FALSE
Bool g_tick = FALSE
Use for control the sampling period value.
static U16 inrush_delay = 0
static Bool inrush_mask_flag = FALSE
Bool overcurrent = FALSE
static U8 ovf_timer = 0
static char State = CONV_INIT
Define Documentation
#define PSWAP0 2
Definition at line 27 of file mc_drv.c.
#define PSWAP1 3
Definition at line 28 of file mc_drv.c.
#define PSWAP2 4
Definition at line 29 of file mc_drv.c.
Function Documentation
__interrupt void ADC_end_of_conversion (void)
Launch the sampling procedure to get current value
Precondition:
amplifier and IT initialization
Postcondition:
Set the End Of Conversion flag
Definition at line 438 of file mc_drv.c.
References Adc_get_10_bits_result, Adc_get_8_bits_result, ADC_INPUT_GND, Adc_select_channel, ADC_State, CONV_CURRENT, CONV_POT, FREE, mc_set_potentiometer_value(), mci_store_measured_current(), and State.
{
  Adc_select_channel(ADC_INPUT_GND); /* release the amplified channel */
  if(State == CONV_POT) mc_set_potentiometer_value(Adc_get_8_bits_result());
  if(State == CONV_CURRENT) mci_store_measured_current(Adc_get_10_bits_result());
  ADC_State = FREE;
}
__interrupt void launch_sampling_period (void)
Launch the regulation loop (see main.c) .
Precondition:
configuration of timer 1 registers
Postcondition:
g_tick use in main.c for regulation loop
Definition at line 339 of file mc_drv.c.
References g_tick, and TRUE.
{
  g_tick = TRUE;
}
void mc_ADC_Scheduler (void)
Launch the scheduler for the ADC
Postcondition:
Get results for Potentiometer and current values.
Definition at line 449 of file mc_drv.c.
Referenced by main().
{
  switch(State)
  {
  case CONV_INIT :
    ADC_State = FREE;
    State = CONV_CURRENT;
    break;
  case CONV_CURRENT :              /* previous state was CONV_CURRENT */
    if(ADC_State == FREE)
    {
      ADC_State = BUSY;
      State= CONV_POT;                        /* new state is CONV_POT */
      Adc_left_adjust_result();
      Adc_start_conv_channel(ADC_INPUT_ISRC); /* get POT on ISRC input */
    }
    break;
  case CONV_POT :                           /* previous state was CONV_POT */
    if(ADC_State == FREE)
    {
      ADC_State = BUSY;
      State = CONV_CURRENT;                   /* new state is CONV_CURRENT */
      Adc_right_adjust_result();
      Adc_start_conv_channel(ADC_INPUT_AMP1); /* get current on amplifier 1 */
    }
    break;
  }
}
void mc_disable_during_inrush (void)
the purpose of this function is to disable
the overcurrent detection during startup (inrush current)
Definition at line 489 of file mc_drv.c.
Referenced by mci_retry_run(), mci_run(), and ushell_task().
{
  inrush_delay = (U16) 500;
  inrush_mask_flag = TRUE;
  Disable_over_current();
}
void mc_duty_cycle (U8 level)
Set the duty cycle values in the PSC according to the value calculate by the regulation loop
Definition at line 227 of file mc_drv.c.
Referenced by main(), mc_switch_commutation(), mci_retry_run(), and mci_run().
{
   U8 duty;
   duty = level;
#if ((CURRENT_DECAY == SLOW_DECAY_SYNCHRONOUS)||(CURRENT_DECAY == FAST_DECAY_SYNCHRONOUS))
   U8 dutydt;   /* duty with dead time */
   if (duty >= DEADTIME) dutydt = duty - DEADTIME;
#endif
   Psc_lock();
  // Duty = 0   => Duty Cycle   0%
  // Duty = 255 => Duty Cycle 100%
#if (CURRENT_DECAY == FAST_DECAY)
   Psc_set_module_A(duty,A_RA_VAL,duty);
   Psc_set_module_B(duty,B_RA_VAL,duty);
   Psc_set_module_C(duty,C_RA_VAL,duty);
#else
#if ((CURRENT_DECAY == SLOW_DECAY_SYNCHRONOUS)||(CURRENT_DECAY == FAST_DECAY_SYNCHRONOUS))
   Psc_set_module_A(duty,A_RA_VAL,dutydt);
   Psc_set_module_B(duty,B_RA_VAL,dutydt);
   Psc_set_module_C(duty,C_RA_VAL,dutydt);
#else
   Psc_set_module_A(duty,A_RA_VAL,0);
   Psc_set_module_B(duty,B_RA_VAL,0);
   Psc_set_module_C(duty,C_RA_VAL,0);
#endif
#endif
   Psc_unlock();
}
void mc_estimation_speed (void)
estimation speed
Precondition:
configuration of timer 0
and define or not AVERAGE_SPEED_MEASURENT in config_motor.h
Postcondition:
new value for real speed
Definition at line 391 of file mc_drv.c.
Referenced by mc_hall_a().
{
  U16 timer_value;
  U32 new_measured_speed;
  if (g_mc_read_enable==TRUE)
  {
    // Two 8 bits variables are use to simulate a 16 bits timers
    timer_value = (ovf_timer<<8) + TCNT0;
    if (timer_value == 0) {timer_value += 1 ;} // warning DIV by 0
    new_measured_speed = K_SPEED / timer_value;
    if(new_measured_speed > 255) new_measured_speed = 255; // Variable saturation
    #ifdef AVERAGE_SPEED_MEASUREMENT
      // To avoid noise an average is realized on 8 samples
      average += new_measured_speed;
      if(count >= N_SAMPLE)
      {
        count = 1;
        mc_set_measured_speed(average >> 3);
        average = 0;
      }
      else count++;
    #else
      // else get the real speed
      mc_set_measured_speed(new_measured_speed);
    #endif
    // Reset Timer 0 register and variables
    TCNT0=0x00;
    ovf_timer = 0;
    g_mc_read_enable=FALSE;
  }
}
Hall_Position mc_get_hall (void)
Get the value of hall sensors (1 to 6)
Parameters:
return an unsigned char value of hall sensor
Precondition:
configuration of port PB and PD
Postcondition:
new value of position
Definition at line 171 of file mc_drv.c.
Referenced by mci_retry_run(), and mci_run().
{
  return HALL_SENSOR_VALUE();
}
__interrupt void mc_hall_a (void)
External interruption Sensor (A) mode toggle
Precondition:
configuration of external interruption (initialization)
Postcondition:
New value in Hall variable
Definition at line 183 of file mc_drv.c.
References FALSE, g_mc_read_enable, HALL_SENSOR_VALUE, mc_estimation_speed(), mc_switch_commutation(), and TRUE.
{
  mc_switch_commutation(HALL_SENSOR_VALUE());
  //estimation speed on rising edge of Hall_A
  if (PIND&(1<<PORTD7))
  {
    mc_estimation_speed();
    g_mc_read_enable=FALSE; // Wait 1 period
  }
  else
  {
    g_mc_read_enable=TRUE;
  }
}
__interrupt void mc_hall_b (void)
External interruption Hall Sensor (B) mode toggle
Precondition:
configuration of external interruption (initialization)
Postcondition:
New value in Hall variable
Definition at line 207 of file mc_drv.c.
References HALL_SENSOR_VALUE, and mc_switch_commutation().
{
  mc_switch_commutation(HALL_SENSOR_VALUE());
}
__interrupt void mc_hall_c (void)
External interruption Hall Sensor (C) mode toggle
Precondition:
configuration of external interruption (initialization)
Postcondition:
New value in Hall variable
Definition at line 219 of file mc_drv.c.
References HALL_SENSOR_VALUE, and mc_switch_commutation().
{
  mc_switch_commutation(HALL_SENSOR_VALUE());
}
void mc_init_HW (void)
mc_init_HW : Hardware Initialization
Postcondition:
initialization of hardware
Definition at line 57 of file mc_drv.c.
Referenced by mc_init().
{
  // Output Pin configuration (used by PSC outputs)
  // PD0 => UH     PB7 => UL
  // PC0 => VH     PB6 => VL
  // PB0 => WH     PB1 => WL
  // Warning Output Low for MOSFET Drivers
  PORTB &= ~(1<<PORTB7 | 1<<PORTB6 | 1<<PORTB1 | 1<<PORTB0);
  PORTC &= ~(1<<PORTC0);
  PORTD &= ~(1<<PORTD0);
  // PORT B :
  DDRB = (1<<DDB7)|(1<<DDB6)|(1<<DDB1)|(1<<DDB0);
  // PORT C :
  DDRC = (1<<DDC0);
  // PORT D :
  DDRD = (1<<DDD0);
  Init_PC7(); /* PC7 is used to display the overcurrent */
  // Disable Digital Input for amplifier1
  // Digital Inputs for comparators are not disabled.
  DIDR1 = (1<<ADC9D)|(1<<ADC8D);
  // Select the Vref Source
//  init_vref_source ();
//  init_adc();
  Adc_config();
  Amp1_config();
  // Be careful : initialize DAC and Over_Current before PWM.
  // DAC is used for oevr current level
  Dac_config();
  /* set the overcurrent level */
  Dac_set_8_bits(IMAX);
  mc_init_timer0();
  mc_init_timer1();
  Comp_0_config();
  Comp_1_config();
  Comp_2_config();
  // Use PCINT14 to detect change on H2 sensor
  PCMSK1 = (1<<PCINT14);
  PCICR = (1<<PCIE1);
//  Start_pll_32_mega(); // Start the PLL and use the 32 MHz PLL output
  Start_pll_64_mega(); // Start the PLL and use the 64 MHz PLL output
  Wait_pll_ready();
  // => PSCx_Init(Period_Half, Dutyx0_Half, Synchro, Dutyx1_Half)
  PSC_Init();
}
void mc_init_timer0 (void)
Timer 0 Configuration The timer 0 is used to generate an IT when an overflow occurs
Precondition:
None
Postcondition:
Timer0 initialized.
Definition at line 356 of file mc_drv.c.
Referenced by mc_init_HW().
{
  TCCR0A = 0;
  TCCR0B = (1<<CS02)|(0<<CS01)|(0<<CS00); // 256 prescaler (16us)
  TIMSK0 = (1<<TOIE0);
}
void mc_init_timer1 (void)
timer 1 Configuration Use to generate a 250us activation for sampling speed regulation
Precondition:
None
Postcondition:
An interrupt all 256us
Definition at line 323 of file mc_drv.c.
Referenced by mc_init_HW().
{
  TCCR1A = 0; //Normal port operation + Mode CTC
  TCCR1B = 1<<WGM12 | 1<<CS11 | 1<<CS10 ; // Mode CTC + prescaler 64
  TCCR1C = 0;
  OCR1AH = 0;
  OCR1AL = 63; // f ocra = 16MHz %64 %63
  TIMSK1=(1<<OCIE1A); // Output compare A Match interrupt Enable
}
void mc_inrush_task (void)
the purpose of this function is to manage the delay
used when the overcurrent detection is disabled
Definition at line 498 of file mc_drv.c.
Referenced by main().
{
  if (inrush_mask_flag == TRUE)
  {
    if (inrush_delay-- == 0)
    {
      inrush_mask_flag = FALSE;
      Enable_over_current();
    }
  }
}
__interrupt void mc_overcurrent_detect (void)
Definition at line 512 of file mc_drv.c.
References mci_stop(), overcurrent, and TRUE.
{
  PIFR = (1<<PEV1); // clear the interrupt
  overcurrent = TRUE;
  mci_stop();
}
void mc_switch_commutation (Hall_Position position)
Set the Switching Commutation value on outputs according to sensor or estimation position
Parameters:
position (1 to 6) and direction (FORWARD or BACKWARD)
Definition at line 267 of file mc_drv.c.
Referenced by mc_hall_a(), mc_hall_b(), mc_hall_c(), mci_retry_run(), and mci_run().
{
  // get the motor direction to commute the right switches.
  char direction = mci_get_motor_direction();
  // Switches are commuted only if the user start the motor
  if (mci_motor_is_running())
  {
    mc_duty_cycle(mc_get_duty_cycle());
    switch(position)
    {
    // cases according to rotor position
      case HS_001:  if (direction==CCW)  {Set_Q5Q2();}
                    else                      {Set_Q1Q6();}
                    break;
      case HS_101:  if (direction==CCW)  {Set_Q3Q2();}
                    else                      {Set_Q1Q4();}
                    break;
      case HS_100:  if (direction==CCW)  {Set_Q3Q6();}
                    else                      {Set_Q5Q4();}
                    break;
      case HS_110:  if (direction==CCW)  {Set_Q1Q6();}
                    else                      {Set_Q5Q2();}
                    break;
      case HS_010:  if (direction==CCW)  {Set_Q1Q4();}
                    else                      {Set_Q3Q2();}
                    break;
      case HS_011:  if (direction==CCW)  {Set_Q5Q4();}
                    else                      {Set_Q3Q6();}
                    break;
      default : break;
      }
  }
  else
  {
    Set_none(); // all switches are switched OFF
  }
}
__interrupt void ovfl_timer0 (void)
Timer0 Overflow for speed measurement
Precondition:
configuration of timer 0
Postcondition:
generate an overflow when the motor turns too slowly
Definition at line 369 of file mc_drv.c.
References mc_set_measured_speed(), mci_motor_is_running(), mci_retry_run(), and ovf_timer.
{
  TCNT0=0x00;
  ovf_timer++;
  // if they are no commutation after 125 ms
  // 125 ms = (61<<8) * 8us
  if(ovf_timer >= 100)
  {
    ovf_timer = 0;
    mc_set_measured_speed(0);
    //if the motor was turning and no stop order
    // was given, motor run automatically.
    if(mci_motor_is_running())mci_retry_run();
  }
}
void PSC_Init (void)
PSC Init : Initialize the PSC according to the settings in config.h
Definition at line 120 of file mc_drv.c.
Referenced by mc_init_HW(), and mci_run().
{
   Psc_set_module_A(A_SA_VAL,A_RA_VAL,A_SB_VAL);
   Psc_set_module_B(B_SA_VAL,B_RA_VAL,B_SB_VAL);
   Psc_set_module_C(C_SA_VAL,C_RA_VAL,C_SB_VAL);
   Psc_set_register_RB(RB_VAL);
   Psc_config();
   Psc_config_input_0(PSC_OVERLAP_ENABLE,\
                      PSC_USE_PIN,\
                      PSC_USE_LOW_LEVEL,\
                      PSC_INPUT_FILTER_ENABLE,\
                      PSC_SYNCHRONOUS_OUTPUT_CONTROL,\
                      PSC_INPUT_NO_ACTION);
   Psc_config_input_1(PSC_OVERLAP_ENABLE,\
                      PSC_USE_COMPARATOR,\
                      PSC_USE_HIGH_LEVEL,\
                      PSC_INPUT_FILTER_ENABLE,\
                      PSC_SYNCHRONOUS_OUTPUT_CONTROL,\
                      PSC_INPUT_NO_ACTION);
   Psc_config_input_2(PSC_OVERLAP_ENABLE,\
                      PSC_USE_PIN,\
                      PSC_USE_LOW_LEVEL,\
                      PSC_INPUT_FILTER_ENABLE,\
                      PSC_SYNCHRONOUS_OUTPUT_CONTROL,\
                      PSC_INPUT_NO_ACTION);
   PIFR = (1<<PEV2)|(1<<PEV1)|(1<<PEV0)|(1<<PEOP);
   PIM = (1<<PEVE1);
   Psc_run();
}
Variable Documentation
char ADC_State = FREE [static]
Definition at line 46 of file mc_drv.c.
Referenced by ADC_end_of_conversion(), and mc_ADC_Scheduler().
U16 average = 0
Definition at line 34 of file mc_drv.c.
Referenced by mc_estimation_speed().
U8 count = 1
Definition at line 33 of file mc_drv.c.
Referenced by mc_estimation_speed().
Bool current_EOC = FALSE
Definition at line 43 of file mc_drv.c.
Bool g_mc_read_enable = FALSE
Definition at line 40 of file mc_drv.c.
Referenced by mc_estimation_speed(), and mc_hall_a().
Bool g_tick = FALSE
Use for control the sampling period value.
Definition at line 41 of file mc_drv.c.
U16 inrush_delay = 0 [static]
Definition at line 38 of file mc_drv.c.
Referenced by mc_disable_during_inrush(), and mc_inrush_task().
Bool inrush_mask_flag = FALSE [static]
Definition at line 37 of file mc_drv.c.
Referenced by mc_disable_during_inrush(), and mc_inrush_task().
Bool overcurrent = FALSE
Definition at line 31 of file mc_drv.c.
U8 ovf_timer = 0 [static]
Definition at line 35 of file mc_drv.c.
Referenced by mc_estimation_speed(), and ovfl_timer0().
char State = CONV_INIT [static]
Definition at line 45 of file mc_drv.c.
Referenced by ADC_end_of_conversion(), and mc_ADC_Scheduler().